dist: xenial
sudo: required
language: cpp

addons:
  apt:
    packages:
      - git
      - libx11-dev
      - freeglut3-dev
      - libxcb-image0-dev
      - libudev-dev
      - libjpeg8-dev
      - libopenal-dev
      - libsndfile1-dev
      - libfreetype6-dev
      - libxrandr-dev
      - unzip
      - wget

before_script:
  - SFML_SOURCE_URL="http://www.sfml-dev.org/files/SFML-2.4.2-sources.zip"
  - CSFML_SOURCE_URL="http://www.sfml-dev.org/files/CSFML-2.4-sources.zip"
  - CSFML_ZIP="CSFML.zip"
  - SFML_ZIP="SFML.zip"
  - echo "Download SFML Sources"
  - curl -Lo "$SFML_ZIP" $SFML_SOURCE_URL
  - echo "Download CSFML Sources"
  - curl -Lo "$CSFML_ZIP" $CSFML_SOURCE_URL
  - echo "Unzip SFML"
  - unzip -qq -o $SFML_ZIP
  - echo "Unzip CSFML"
  - unzip -qq -o $CSFML_ZIP
  - mv SFML-* SFML
  - mv CSFML-* CSFML
  - SFML_PATH="$(realpath SFML)"
  - CSFML_PATH="$(realpath CSFML)"
  - echo "SFML Compilation"
  - cd SFML
  - cmake .
  - make
  - cd ..
  - echo "CSFML Compilation"
  - cd CSFML
  - cmake -DSFML_ROOT="$SFML_PATH" -DSFML_INCLUDE_DIR="$SFML_PATH/include" -DCMAKE_MODULE_PATH="$SFML_PATH/cmake/Modules" .
  - LD_LIBRARY_PATH="$SFML_PATH/lib"
  - make
  - sudo make install
  - cd ..
  - echo '/usr/local/lib/' | sudo tee --append /etc/ld.so.conf.d/csfml.conf > /dev/null
  - sudo ldconfig
  - rm -rf "$CSFML_ZIP" "$CSFML_PATH" "$SFML_ZIP" "$SFML_PATH"
  - URL="https://github.com/Snaipe/Criterion/releases/download/v2.3.2"
  - TARBALL="criterion-v2.3.2-linux-x86_64.tar.bz2"
  - DIR="criterion-v2.3.2"
  - DST="/usr/local/"
  - cd /tmp
  - rm -f $TARBALL
  - rm -fr $DIR
  - wget $URL/$TARBALL
  - tar xjf $TARBALL
  - echo "creating custom ld.conf"
  - sudo sh -c "echo "/usr/local/lib" > /etc/ld.so.conf.d/criterion.conf"
  - echo "cp headers to $DST/include..."
  - sudo cp -r $DIR/include/* $DST/include/
  - echo "cp lib to $DST/include..."
  - suo cp -r $DIR/lib/* $DST/lib/
  - echo "run ldconfig."
  - sudo ldconfig
  - echo "all good."

script:
  - make tests_run