dist: xenial
sudo: required
language: cpp

addons:
  apt:
    packages:
      - git
      - libx11-dev
      - freeglut3-dev
      - libxcb-image0-dev
      - libudev-dev
      - libjpeg8-dev
      - libopenal-dev
      - libsndfile1-dev
      - libfreetype6-dev
      - libxrandr-dev
      - unzip
      - bash

script:
  - sudo bash ./install_script.sh
  - make tests_run